create table if not exists checklist_submissions (
  id integer primary key autoincrement,
  branch text,
  department text,
  date text,
  installation_date text,
  staff_name text,
  user_full_name text,
  staff_id_number text,
  pc_nb_number text,
  new_serial_number text,
  old_pc_serial_number text,
  new_pc_serial_number text,
  new_pc_serial_number_confirm text,
  old_monitor_serial_number text,
  new_monitor_serial_number text,
  new_monitor_serial_number_confirm text,
  old_hostname text,
  new_hostname text,
  old_ip_address text,
  new_ip_address text,
  ip_address text,
  pc_serial_remark text,
  monitor_serial_remark text,
  hostname_remark text,
  ip_address_remark text,
  before_replace text,
  after_replace text,
  verification text,
  remark text,
  status text,
  engineer_name text,
  user_name text,
  created_at text not null
);
