create table if not exists public.checklist_submissions (
  id bigint generated by default as identity primary key,
  branch text,
  department text not null,
  date date,
  user_full_name text not null,
  installation_date date,
  staff_name text,
  staff_id_number text,
  pc_nb_number text,
  new_hostname text,
  old_pc_serial_number text,
  new_pc_serial_number text,
  new_pc_serial_number_confirm text,
  old_monitor_serial_number text,
  new_monitor_serial_number text,
  new_monitor_serial_number_confirm text,
  old_ip_address text,
  new_ip_address text,
  new_serial_number text not null,
  old_hostname text,
  ip_address text,
  pc_serial_remark text,
  monitor_serial_remark text,
  hostname_remark text,
  ip_address_remark text,
  software_flags jsonb not null default '{}'::jsonb,
  additional_software text,
  before_replace jsonb not null default '[]'::jsonb,
  after_replace jsonb not null default '[]'::jsonb,
  verification jsonb not null default '{}'::jsonb,
  engineer_name text,
  user_name text,
  status text not null default 'Pending',
  remark text,
  created_at timestamptz not null default now()
);

alter table public.checklist_submissions
add column if not exists branch text;

alter table public.checklist_submissions
add column if not exists date date;

alter table public.checklist_submissions
add column if not exists staff_name text;

alter table public.checklist_submissions
add column if not exists staff_id_number text;

alter table public.checklist_submissions
add column if not exists pc_nb_number text;

alter table public.checklist_submissions
add column if not exists old_pc_serial_number text;

alter table public.checklist_submissions
add column if not exists new_pc_serial_number text;

alter table public.checklist_submissions
add column if not exists new_pc_serial_number_confirm text;

alter table public.checklist_submissions
add column if not exists old_monitor_serial_number text;

alter table public.checklist_submissions
add column if not exists new_monitor_serial_number text;

alter table public.checklist_submissions
add column if not exists new_monitor_serial_number_confirm text;

alter table public.checklist_submissions
add column if not exists old_ip_address text;

alter table public.checklist_submissions
add column if not exists new_ip_address text;

alter table public.checklist_submissions
add column if not exists ip_address text;

alter table public.checklist_submissions
add column if not exists pc_serial_remark text;

alter table public.checklist_submissions
add column if not exists monitor_serial_remark text;

alter table public.checklist_submissions
add column if not exists hostname_remark text;

alter table public.checklist_submissions
add column if not exists ip_address_remark text;

alter table public.checklist_submissions
add column if not exists verification jsonb not null default '{}'::jsonb;

alter table public.checklist_submissions enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert on public.checklist_submissions to anon, authenticated;

drop policy if exists "Allow public read" on public.checklist_submissions;
create policy "Allow public read"
on public.checklist_submissions
for select
using (true);

drop policy if exists "Allow public insert" on public.checklist_submissions;
create policy "Allow public insert"
on public.checklist_submissions
for insert
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'checklist_submissions'
  ) then
    alter publication supabase_realtime add table public.checklist_submissions;
  end if;
end
$$;
