create table if not exists public.checklist_submissions (
  id bigint generated by default as identity not null,
  department text not null,
  user_full_name text not null,
  installation_date date null,
  new_hostname text null,
  new_serial_number text not null,
  old_hostname text null,
  software_flags jsonb not null default '{}'::jsonb,
  additional_software text null,
  before_replace jsonb not null default '[]'::jsonb,
  after_replace jsonb not null default '[]'::jsonb,
  engineer_name text null,
  user_name text null,
  status text not null default 'Pending'::text,
  remark text null,
  created_at timestamp with time zone not null default now(),
  branch text null,
  date date null,
  staff_name text null,
  staff_id_number text null,
  pc_nb_number text null,
  old_pc_serial_number text null,
  new_pc_serial_number text null,
  new_pc_serial_number_confirm text null,
  old_monitor_serial_number text null,
  new_monitor_serial_number text null,
  new_monitor_serial_number_confirm text null,
  old_ip_address text null,
  new_ip_address text null,
  ip_address text null,
  pc_serial_remark text null,
  monitor_serial_remark text null,
  hostname_remark text null,
  ip_address_remark text null,
  verification jsonb not null default '{}'::jsonb,
  constraint checklist_submissions_pkey primary key (id)
) TABLESPACE pg_default;

alter table public.checklist_submissions
add column if not exists branch text;

alter table public.checklist_submissions
add column if not exists date date;

alter table public.checklist_submissions
add column if not exists staff_name text;

alter table public.checklist_submissions
add column if not exists staff_id_number text;

alter table public.checklist_submissions
add column if not exists pc_nb_number text;

alter table public.checklist_submissions
add column if not exists old_pc_serial_number text;

alter table public.checklist_submissions
add column if not exists new_pc_serial_number text;

alter table public.checklist_submissions
add column if not exists new_pc_serial_number_confirm text;

alter table public.checklist_submissions
add column if not exists old_monitor_serial_number text;

alter table public.checklist_submissions
add column if not exists new_monitor_serial_number text;

alter table public.checklist_submissions
add column if not exists new_monitor_serial_number_confirm text;

alter table public.checklist_submissions
add column if not exists old_ip_address text;

alter table public.checklist_submissions
add column if not exists new_ip_address text;

alter table public.checklist_submissions
add column if not exists ip_address text;

alter table public.checklist_submissions
add column if not exists pc_serial_remark text;

alter table public.checklist_submissions
add column if not exists monitor_serial_remark text;

alter table public.checklist_submissions
add column if not exists hostname_remark text;

alter table public.checklist_submissions
add column if not exists ip_address_remark text;

alter table public.checklist_submissions
add column if not exists verification jsonb not null default '{}'::jsonb;

alter table public.checklist_submissions enable row level security;

grant usage on schema public to anon, authenticated;
grant select, insert on public.checklist_submissions to anon, authenticated;

drop policy if exists "Allow public read" on public.checklist_submissions;
create policy "Allow public read"
on public.checklist_submissions
for select
using (true);

drop policy if exists "Allow public insert" on public.checklist_submissions;
create policy "Allow public insert"
on public.checklist_submissions
for insert
with check (true);

do $$
begin
  if not exists (
    select 1
    from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'checklist_submissions'
  ) then
    alter publication supabase_realtime add table public.checklist_submissions;
  end if;
end
$$;
